services:
# Api principal que se encargará de crear las APIs dinámicamente.
  api:
    build:
      context: ./api
    restart: unless-stopped
    env_file:
      - ./api/.env
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./api:/api
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/nginx/conf.d/apis:/etc/nginx/conf.d/apis
    environment:
      - PYTHONPATH=/api
    depends_on:
      - postgres
      - mariadb
      - mysql

  appweb:
    build:
      context: ./appWeb
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - api
# Base de datos para las apis:
  postgres:
    image: postgres
    restart: unless-stopped
    command: postgres -c shared_buffers=32MB -c max_connections=50
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    mem_limit: 256m
    networks:
      - default
      - api_default

  mariadb:
    image: mariadb
    restart: unless-stopped
    command: --innodb-buffer-pool-size=64M --max-connections=50 --performance-schema=OFF
    environment:
      MARIADB_ROOT_USER: root
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: mariadb
      MARIADB_USER: user
      MARIADB_PASSWORD: password
    ports:
      - "127.0.0.1:5433:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    mem_limit: 256m
    networks:
      - default
      - api_default

  mysql:
    image: mysql
    restart: unless-stopped
    command: --innodb-buffer-pool-size=64M --max-connections=50 --performance-schema=OFF
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "127.0.0.1:5434:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    mem_limit: 256m
    networks:
      - default
      - api_default

  # Luego se agregarán las demás bases de datos aquí, siguiendo el ejemplo de PostgreSQL.

# !!IMPORTANTE!!: No eliminar el bloque de volúmenes, es necesario para la persistencia de datos de Postgre base de datos y si se
# añaden más bases de datos se tiene que hacer su volumen.
volumes:
  postgres_data:
  mariadb_data:
  mysql_data:

networks:
  api_default:
    external: true