// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-l4wevzwLNuoeuUrv8gWqnqbbkUBt0-M',
    appId: '1:181457370400:web:dc460dc4f9c86cbef82b45',
    messagingSenderId: '181457370400',
    projectId: 'gestion-api-rest-dam',
    authDomain: 'gestion-api-rest-dam.firebaseapp.com',
    storageBucket: 'gestion-api-rest-dam.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKjO_vwfFths5YS_qPIvzgvsfHdvfQxi4',
    appId: '1:181457370400:android:7c853e591068f7f6f82b45',
    messagingSenderId: '181457370400',
    projectId: 'gestion-api-rest-dam',
    storageBucket: 'gestion-api-rest-dam.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPJGaOWUKUQkV1waos4cv7YvRPm9XVYaI',
    appId: '1:181457370400:ios:59c27753289a54d6f82b45',
    messagingSenderId: '181457370400',
    projectId: 'gestion-api-rest-dam',
    storageBucket: 'gestion-api-rest-dam.firebasestorage.app',
    iosBundleId: 'com.example.tfg2damaGestionApirest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPJGaOWUKUQkV1waos4cv7YvRPm9XVYaI',
    appId: '1:181457370400:ios:59c27753289a54d6f82b45',
    messagingSenderId: '181457370400',
    projectId: 'gestion-api-rest-dam',
    storageBucket: 'gestion-api-rest-dam.firebasestorage.app',
    iosBundleId: 'com.example.tfg2damaGestionApirest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-l4wevzwLNuoeuUrv8gWqnqbbkUBt0-M',
    appId: '1:181457370400:web:a434df28286243f7f82b45',
    messagingSenderId: '181457370400',
    projectId: 'gestion-api-rest-dam',
    authDomain: 'gestion-api-rest-dam.firebaseapp.com',
    storageBucket: 'gestion-api-rest-dam.firebasestorage.app',
  );
}
